language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rmanish/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rmanish/docker-react npm run test
  # - docker run rmanish/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-travis"
  env: "Dockerreacttravis-env"
  bucket_name: "elasticbeanstalk-us-east-2-687997792686"
  bucket_path: "docker-react-travis"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY